### ISSUE TITLE
CA201-Internals-IdentityProtection-AnyApp-AnyPlatform-BLOCK-HighRisk

### ISSUE THREAD

**Issue by ChrisFDSTech** [j0eyv/ConditionalAccessBaseline#1]

**Comment by j0eyv** [comment]
Sorry. Have not seen this issue until i received the close email.

**Comment by ChrisFDSTech** [comment]
No worries, I have determined in my test environment that the licensing is incorrect, so the policy does not import.

**Comment by j0eyv** [comment]
> No worries, I have determined in my test environment that the licensing is incorrect, so the policy does not import.

Policies CA203, CA205 and CA208 could have importing issues if app “Microsoft Intune Enrollment” does not exist. Therefor you need to run the following comment:

New-AzureADServicePrincipal -AppId d4ebce55-015a-49b5-a083-c84d1797ae8c

Once completed you are able to include/exclude this app or re-import the policies.

**Comment by ChrisFDSTech** [comment]
It appears I already have this in my environment.

***@***.***

Correct me if I am wrong. I only have a P1 license though and I think I need a P2.

Thanks,

CHRIS BRAEUER
IT Support Specialist

***@***.***<https://www.fdstech.com/>

Future Data Systems, Inc. | 2017 Hope Mills Road | Fayetteville, NC 28304
Phone: 910.483.5395 | Fax: 910.725.6124
***@***.******@***.***> | www.fdstech.com<http://www.fdstech.com/>

**Comment by j0eyv** [comment]
You dont need P2. Send me a DM on linkedin.
